server:
  port: ${PORT:5000}
spring:
  jackson:
    serialization:
      indent_output: true
  application:
    name: "heroku-scheduler-app"
  zipkin:
    baseUrl: ${ZIPKIN_PORT:http://localhost}

scheduler:
  enabled: ${SCHEDULER_ENABLED:true}