server:
  port: ${PORT:8081}

sse:
  evicting-queue:
    max-size: ${MAX_QUEUE_SIZE:7}

spring:
  jackson:
    serialization:
      indent_output: true
  application:
    name: heroku-scheduler-app
  zipkin:
    baseUrl: ${ZIPKIN_PORT:http://127.0.0.1:9411}
    enabled: ${ZIPKIN_ENABLED:false}
  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      uri: ${MONGODB_URI}

scheduled:
  task:
    job:
      cron: ${SCHEDULER_CRONE:*/5 * * * * *}

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: ${SPRING_ACTUATOR_ENABLED:false}